PrimeEwsi/Controllers/JiraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json.Linq;
using PrimeEwsi.Infrastructure;
using PrimeEwsi.Models;
using RestSharp;

namespace PrimeEwsi.Controllers
{
    [HandleErrorException]
    public class JiraController : Controller
    {
        // GET: Jira
        public ActionResult Authentication()
        {
            var model = new JiraModel
            {
                UserSkp = this.HttpContext.User.Identity.Name.Substring(9)
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult SetCookie(string user, string password)
        {
            var model = new JiraModel();

            var restClient = new RestClient("https://godzilla.centrala.bzwbk:9999");

            var request = new RestRequest("/rest/auth/1/session", Method.POST);

            request.AddJsonBody(new { username = user, password = password });

            var response = restClient.Execute(request).Content;

            var jResponse = JObject.Parse(response);

            model.Cookie = jResponse["session"]["value"].ToString();

            return View("Authentication", model);
        }
    }
}

PrimeEwsi/Views/Jira/Authentication.cshtml
@using System.Web.Optimization
@model PrimeEwsi.Models.JiraModel
@{
    ViewBag.Title = "Authentication";
}

<h2>Authentication</h2>


@if (!string.IsNullOrEmpty(Model.Cookie))
{
    <div class="alert alert-success fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Success!</strong> Your JIRA cookie is  <span id="copyArea">@Model.Cookie</span> <button class="js-textareacopybtn"><i class="fa fa-clipboard" aria-hidden="true"></i></button>
    </div>
}

<div class="panel panel-primary" style="width: 70%; margin-top: 20px">

    <div class="panel-heading">
        <h3 class="panel-title">Add Pack</h3>
    </div>

    <div class="panel-body">

        @using (Html.BeginForm("SetCookie", "Jira", FormMethod.Post))
        {
            <div class="form-group">
                <label for="usr">Name:</label>
                <input type="text" class="form-control" id="user" Name="user" value="@Model.UserSkp">
            </div>
            <div class="form-group">
                <label for="pwd">Password:</label>
                <input type="password" class="form-control" id="password" Name="password">
            </div>

            <button type="submit" class="btn btn-primary">Confirm</button>

        }


    </div>
</div>
@Scripts.Render("~/bundles/view-autorization")